### ISSUE TITLE
Feature Request: WordCount cog reacts to input. 

### ISSUE THREAD

**Issue by i-am-zaidali** [TheF1ng3r/finger-cogs#1]
Much like ObiWan's counting cog i would like the wordcount cog to react to the input whether it is correct or incorrect. Ofcourse that makes it clear that correct input gets reacted with a ✔️ and wrong input gets reacted with a ❌. There should be a setting for guild to enable/disable this too if they want. Also if possible (and deemed worthy) if this frature is enabled in a server, the bot automatically puts a 3-4s cooldown on the channel so that it doesnt get ratelimited while reacting (although i highly doubt any server would be counting that fast in words). I could make a pull request for this if u want.

**Comment by i-am-zaidali** [comment]
oh wait nvm i didnt notice it already does react. However the ability to enable/disable this feature would still be highly useful :)

**Comment by AdamTuraj** [comment]
You can enable/disable the cog, if that's what you mean

**Comment by i-am-zaidali** [comment]
No i meant, enabling/disabling the react feature where the bot reacts if the count is correct.

**Comment by AdamTuraj** [comment]
I'll think about it
